#!/bin/bash

cd /home/pi
mkdir -p node-red
rm docker-compose.yml
wget  --no-check-certificate https://github.com/Audumla/audiot-rpi-nodered/raw/master/docker-compose.yml
if grep -l v7l /proc/cpuinfo
then
    sed -i 's/audumla\/audiot-rpi-nodered/audumla\/audiot-rpi-nodered:v7l/g' docker-compose.yml
else
    sed -i 's/audumla\/audiot-rpi-nodered/audumla\/audiot-rpi-nodered:v6l/g' docker-compose.yml
fi

